version: 2

project_name: afcli

builds:
  - main: ./cmd/afcli
    binary: afcli
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X github.com/rie03p/appsflyer-cli/internal/cli.Version={{.Version}}

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

changelog:
  use: github
  filters:
    exclude:
      - '^docs(\(.+\))?:'
      - '^ci(\(.+\))?:'
      - '^chore(\(.+\))?:'
      - "^Merge pull request"
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1
    - title: Performance
      regexp: '^.*?perf(\(.+\))??!?:.+$'
      order: 2
    - title: Other
      order: 999
